# Introduction To Numpy
 nympy in.......
 discription here 

In [4]:
 # Numpy Arrays
 # 2 types fo array: as a vector 1d and matris 2d
# if it has 2 [[]] then it is 2 dimnational arry or having [] 1 bracket is i one dimantionaöl array 
import numpy as np 
list_1 =([1,2,3,4])
list_1

[1, 2, 3, 4]

In [6]:
np.array(list_1)

array([1, 2, 3, 4])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.linspace(0,200,201) # 1 to 100 equal distance between the eliment 

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# numpy randon modules
np.random.rand(3)


array([0.39473509, 0.25938252, 0.23367055])

In [19]:
np.random.rand(3,4)

array([[0.97742509, 0.7190102 , 0.30173894, 0.81072138],
       [0.40015674, 0.73355607, 0.10056768, 0.98720681],
       [0.52951396, 0.38523754, 0.53282018, 0.20298883]])

In [20]:
# Randn 
np.random.randn(5)


array([-0.00131221, -0.03579195, -0.94525971, -1.1104927 ,  0.78145929])

In [21]:
np.random.rand(3,5)

array([[0.06271735, 0.88086663, 0.59159059, 0.7147286 , 0.46469179],
       [0.40557008, 0.54916094, 0.93673548, 0.03919592, 0.04836819],
       [0.80727096, 0.3892552 , 0.79941673, 0.71323728, 0.97487085]])

In [23]:
arr = np.arange(1,20,2)
arr


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
arr.reshape(5,2) # reshape The array in to 2/2 matrix

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [26]:
arr.max()


19

In [27]:
arr.min()

1

In [29]:
arr.argmax()# index with heighest value

9

# numpy Operation


In [31]:
arr2= np.arange (1,10)
arr3= np.arange (11,20) 

In [32]:
arr2 + arr3 # aad same nuimber in the matris with same position # same matrix can be do add

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [33]:
arr2 * arr3 

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [34]:
arr2 ** arr3

array([          1,        4096,     1594323,   268435456,   452807053,
        -683606016, -2094633337,           0,  -400556711], dtype=int32)

In [35]:
arr2 ** 4


array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

# NUMpy Indexing and selection 

In [37]:
example_arr = np.arange(1,21).reshape(4,5)


In [38]:
example_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
example_arr[:2]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
example_arr[:2,:2]


array([[1, 2],
       [6, 7]])

In [48]:
example_arr[ :2, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

# broadcasting 

In [52]:
example_arr[1:4] = 30 

In [53]:
example_arr

array([[ 1,  2,  3,  4,  5],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [54]:
example_arr[3]= [2,3,4,5,6]

In [55]:
example_arr

array([[ 1,  2,  3,  4,  5],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [ 2,  3,  4,  5,  6]])

# conditional selection 


In [59]:
example_arr2 = np.arange(21,41).reshape(4,5)


In [60]:
example_arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [65]:
example_arr2[(example_arr2 > 30) & (example_arr2 < 35)]

array([31, 32, 33, 34])